language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
  - node_modules

before_install:

  # Make sure we're running the latest version of Yarn.
  # @see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn
- travis_retry curl -o- --location https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn --version
  - yarn lint

deploy:
  provider: npm
  email: tdmalone@gmail.com
  api_key:
    secure: bgazhrCqsB1yB41yfvVxyDdXhl6Z1ZHevuIwXwAZO/M1UhKLSGTSXZAvOGSJATnsIYfQGEA4NlApnFTRXdCuMjkGEHFFG8AOwPZpV6HU/ejAJR28GQT4ZEVfY+ptjqNhYeXaXKW8xlScgC+6xhUWSJzP97ODa94YQP8qw70RbhkJiqcWdjWZBJq2Jb5jfIznC/HlTpEOx2T6sRVmy3mnRENEpc9ZVYvSEUSSnte8Bf6qesKnuWbu+ce8aFByQC5A/dSo2B/Z3x5uECA5LnzU0IKW0/nLsfOwba4/TFPTozs/q478KwWMuHMAYR5dqgIXZW2JvTzmEuceYz52CSf3VXZow/+6ETf1prTJiPdKC6OHf4UfMYP6JZ9lWkYQqcpFHv0zfv0jItb9ovmTmz5SpgvA4tpXtx2oL9mdovXnyFA6t+Ew4FggjH0l3uvKgEqSqOwDgVqxaJD+tJ3i31Y27Ir5Y0lGpUs/g118UfTGHaS7eWW82L5VxOhNqVzIEqzmzfLSJQtvKR1TSWKKDXzImepu1xk/PtliSK2EXdMrT0V1+C2o5DKSsjIjCMD85RshLx6vEb1/0CKB7v90QCx8Rkp6JdsbxMy9ehBp2fK7CP7nEAeoeVFooz2x73CbVmtzl+BYz+IWnlBxkgewp9p5gYp9b/07izcLQe2PpRF5u7A=
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: "mwvOfCsPz3s8I4ycMhLBGhM3wZF8vCnEpPjk1SyXsYKFJKABwggb52j2XY6FZcnzqMUtuklWMuTmox0jPqWUrU6ckf92TgR2BhS5OnFWozBDPo5rUg5bPIGU+hrc/CUUO9R5O9wWOIkQpS5jv6H/aTpPyM60AL0DMun/vK9Bm+OGeVO0Pmv3vcOhDiNsf+3tF8ci9cmMOSwNIcVt4N3xNW7gkwiyVfKn0BZ9i2rnBNTo/fuOHZafpOVUnBbw01YIpE11OuBeIEy8qEqtAtsRIOBciv8sXXnSpHIxtijkYI6alldE5LqNHYRW1hF6EQmhk6E4NO5nHMFP5KgFMvFfZyHjhrU//53x8yLYbBngH/ClB86JnqxgBtXL1wU2Rz1ODsiy9f6RWf/3Jkvl+atT6ccO2++GwJLfFGdUCw50cOgQ4iq2a4pvcjaASkuga8bbYvHl+EWONBIZz/i45OQxd7KZ1c5NoGso+M795IzxhxRJO2xuAdjsQvtc0fF4AC+wYB61aGeX4iL10Uzcl6SGNRXu6P7F8CiT4FIe+VJcYyXFDj4rzPXniBuS+2Jk3jOfMB9uLIJvF8Jx37EsXL3YzlraF2l4QzWBtvjRMckjTC/0f7/IN+oNBI2Ex88IbJQLjODYt/HFhZ6SbgNNVDNE3+R0CmNUW/P2f/oBMS6aADs="
    on_start: always
